name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./OrderManagement/pom.xml
          mvn clean package -f ./Delivery/pom.xml
          mvn clean package -f ./RestaurantMenu/pom.xml
          mvn clean package -f ./UserAccessControl/pom.xml
          mvn clean package -f ./StatisticsReporting/pom.xml

      - name: Docker Build and push for OrderManagement
        uses: docker/build-push-action@v4
        with:
          context: ./OrderManagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ordermanagement:latest
            ghcr.io/${{ github.repository }}/ordermanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Delivery
        uses: docker/build-push-action@v4
        with:
          context: ./Delivery
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/delivery:latest
            ghcr.io/${{ github.repository }}/delivery:${{ github.ref_name }}
            
      - name: Docker Build and push for RestaurantMenu
        uses: docker/build-push-action@v4
        with:
          context: ./RestaurantMenu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/restaurantmenu:latest
            ghcr.io/${{ github.repository }}/restaurantmenu:${{ github.ref_name }}
            
      - name: Docker Build and push for UserAccessControl
        uses: docker/build-push-action@v4
        with:
          context: ./UserAccessControl
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/useraccesscontrol:latest
            ghcr.io/${{ github.repository }}/useraccesscontrol:${{ github.ref_name }}
            
      - name: Docker Build and push for StatisticsReporting
        uses: docker/build-push-action@v4
        with:
          context: ./StatisticsReporting
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/statisticsreporting:latest
            ghcr.io/${{ github.repository }}/statisticsreporting:${{ github.ref_name }}
            
