server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: OrderManagement
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, /reviews/**, /carts/**, /orderStatusLists/**, /orderDetails/**, /restaurantOrderStatusLists/**, /reviewLists/**, /reviewDetails/**, /cartDetails/**, /cartLists/**
        - id: Delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, /riders/**, /deliveryTrackings/**, /deliveryOrderPaths/**, /riderDeliveryLists/**, /riderDeliveryDetails/**
        - id: RestaurantMenu
          uri: http://localhost:8084
          predicates:
            - Path=/restaurants/**, /nearbyRestaurantLists/**, /restaurantDetails/**, /menuLists/**
        - id: UserAccessControl
          uri: http://localhost:8085
          predicates:
            - Path=/users/**, /phoneVerifications/**, /userListViews/**, /userDetailViews/**, /phoneVerificationLists/**, /phoneVerificationDetails/**
        - id: StatisticsReporting
          uri: http://localhost:8086
          predicates:
            - Path=/reports/**, /reportData/**, /reportLists/**, /reportDetails/**, /reportVisualizations/**, /reportDownloads/**, /statisticsDataLists/**, /statisticsDataVisualizations/**, /statisticsDataDownloads/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: OrderManagement
          uri: http://orderManagement:8080
          predicates:
            - Path=/orders/**, /reviews/**, /carts/**, 
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, /riders/**, 
        - id: RestaurantMenu
          uri: http://restaurantMenu:8080
          predicates:
            - Path=/restaurants/**, 
        - id: UserAccessControl
          uri: http://userAccessControl:8080
          predicates:
            - Path=/users/**, /phoneVerifications/**, 
        - id: StatisticsReporting
          uri: http://statisticsReporting:8080
          predicates:
            - Path=/reports/**, /reportData/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
