apiVersion: apps/v1
kind: Deployment
metadata:
  name: UserAccessControl
  labels:
    app: UserAccessControl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UserAccessControl
  template:
    metadata:
      labels:
        app: UserAccessControl
    spec:
      containers:
        - name: UserAccessControl
          image: "username/UserAccessControl:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
